eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: 
        username: 
        password: 
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                hibernate:
                    ddl-auto: update

